### ISSUE TITLE
Make the test suite work even without network connection (this is not the right solution)

### ISSUE THREAD

**Issue by mcepl** [fsspec/gcsfs#292]
**What happened**:
All builds (and running test suites as part of them) of OpenSUSE packages (the same for every other Linux distribution) happen in the chrooted environment without the network access, which makes running of the test suite for this package extremely awkward. Most of tests fail because they require network access, which is a bad idea even for other reasons (mocking is the way to go).

**What you expected to happen**:
All tests are using mock and work without even accessing network.

**Anything else we need to know?**:
[avoid_network_tests.patch](https://github.com/dask/gcsfs/files/5336173/avoid_network_tests.patch.txt) is the solution of my problem, marking all tests requiring network access appropriately, and then skipping so marked ones, but the result is extremely awkward (“8 tests passed, 7 skipped, 54 deselected, 3 xfailed in 0.67s”), so this is more a plea for using more mock for testing.

**Environment**:

- Dask version: ??? included?
- Python version: 3.8
- Operating System: Linux/OpenSUSE/Tumbleweed
- Install method (conda, pip, source): OpenSUSE Packages

**Comment by martindurant** [comment]
The test suite does NOT use the network, all responses are replayed from recordings that were made against the real storage system using `vcrpy`, a mocking package meant specifically for this purpose.

**Comment by mcepl** [comment]
> The test suite does NOT use the network, all responses are replayed from recordings that were made against the real storage system using `vcrpy`, a mocking package meant specifically for this purpose.

With the package `python3-vcrpy-4.1.0-29.3` installed when running without any limits on `pytest` I get all those errors as recorded in [the full build log](https://github.com/dask/gcsfs/files/5337034/_log.txt) (you can see also all version of all packages installed). Any idea, what do I do wrong?

**Comment by bnavigator** [comment]
This has been fixed by using the GitHub tarball. The VCR recordings are not packaged with the PyPI sdist.
