### ISSUE TITLE
What is the purpose of auth.py

### ISSUE THREAD

**Issue by DPGrev** [fsspec/gcsfs#332]
So I have been going through the code of [auth.py](https://github.com/dask/gcsfs/blob/master/gcsfs/auth.py) and I was wondering what the purpose of this piece of code is. What is the goal and when is it executed?

**Comment by martindurant** [comment]
Apparently it i vestigial, removing it is completely fine. It was an attempt to solve the browser OAuth dance ( https://github.com/dask/gcsfs/issues/261 ), which remains a problem.
