### ISSUE TITLE
Regression in `_get_file`

### ISSUE THREAD

**Issue by mouradmourafiq** [fsspec/gcsfs#433]
**What happened**:

This commit introduced a regression:  https://github.com/dask/gcsfs/commit/552ccb3735b9bcfe153977ca78fa842b05ad59bf#diff-efbb8d206455e951a2ed240275e4d88d01119dbefa1dbd37a18a0ab49da334b1R1027

More details can be found here: https://github.com/dask/gcsfs/pull/419#issuecomment-961823856

I understand the reasons behind the commit and I believe that we should find a better (performant) solution to make the check without having to make the http calls to verify if the blob is a dir or a file.

**What you expected to happen**:

The check to be re-introduced:

```python

    async def _get_file(self, rpath, lpath, callback=None, **kwargs):
        if await self._isdir(rpath):
            return
        u2 = self.url(rpath)
        await self._get_file_request(u2, lpath, callback=callback, **kwargs)
```

Or the recursive logic should not attempt at loading the file when iterating over the `ls` results.

**Minimal Complete Verifiable Example**:

Try downloading a deeply nested dir:

```python
fs.download(rpath=path_from, lpath=path_to, recursive=True)
```

The download will fail randomly at some nested directory when it will attempt performing a download.
Retrying the command will fail at another directory.

**Anything else we need to know?**:

You can check the same behavior between version, i.e. `gcsfs<2021.9.0` and `gcsfs>=2021.9.0`.

**Environment**:

- Dask version: n/a
- Python version: 3.9
- Operating System: ubuntu/mac
- Install method (conda, pip, source): pip

**Comment by mouradmourafiq** [comment]
@martindurant any ideas about this issue or if I should be looking at another source of the regression. 

Note that I had to reintroduce the check in order to perform the operation : `fs.download(rpath=path_from, lpath=path_to, recursive=True)` with the version `gcsfs==2021.9.0`

**Comment by martindurant** [comment]
The current version, just released, has [this line](https://github.com/fsspec/gcsfs/blob/main/gcsfs/core.py#L1120) - does this solve things for you?

**Comment by mouradmourafiq** [comment]
Oh perfect, that's exactly the change that I had to re-introduce 👍

**Comment by martindurant** [comment]
It's not *quite* the same, as it checks the local path, but those paths should have been created as directories already.

**Comment by mouradmourafiq** [comment]
it's even better because it's not only the same check (is_dir), but it does not require doing it over the network (i.e. GCS)
