### ISSUE TITLE
Problem with cache when using custom prefix in find method

### ISSUE THREAD

**Issue by piotrpiatyszek** [fsspec/gcsfs#436]
Hello, we are using GCSFS as a backend for a DVC repository. Because filenames in this repository are md5 sums of the content, then DVC counts files starting with '0' to estimate the total number of all files.

After some failed synchronization I have found a problem with the `find` method. Here is the example, that adding one find method changes the output of the other.
```
>>> import gcsfs
>>> fs = gcsfs.GCSFileSystem()
>>> fs.find('bucket-name/MARS/00/10dfaf8c125ab344f3a22cbf6e6c3e')
['bucket-name/MARS/00/10dfaf8c125ab344f3a22cbf6e6c3e']
```
```
>>> import gcsfs
>>> fs = gcsfs.GCSFileSystem()
>>> fs.find('gs://bucket-name', prefix="MARS/00/0")
['bucket-name/MARS/00/06890feb13f64892f8154575ae3371']
>>> fs.find('bucket-name/MARS/00/10dfaf8c125ab344f3a22cbf6e6c3e')
[]
```
From my observations method `_find` puts only files starting with `0` to `dircache` with key `bucket-name/MARS/00`. Then method `_get_object` raises FileNotFoundError, because cache exists and there is no file `10dfaf8c125ab344f3a22cbf6e6c3e` in this cache.

**Comment by martindurant** [comment]
I daresay that if there is a `prefix`, we shouldn't be checking the cache at all - thoughts, @isidentical ?

**Comment by isidentical** [comment]
> I daresay that if there is a prefix, we shouldn't be checking the cache at all - thoughts, @isidentical ?

Agreed. `prefix` and cache doesn't work well.
