### ISSUE TITLE
Doesn't work for a file path containing a hashtag (`#`)

### ISSUE THREAD

**Issue by kornosk** [fsspec/gcsfs#447]
The lib cannot read a file with the file path containing `#`. Weird thing is that it has no error too, just nothing is read. A silent bug.

```python
fs = gcsfs.GCSFileSystem()

# Nothing printed out
data = fs.open("gs://sample_project/my_folder/#this_is_file.json")
print(data.read())
data.close()

# Then I change the file name to remove `#`
# This works
data = fs.open("gs://sample_project/my_folder/this_is_file.json")
print(data.read())
data.close()
```

Not sure if there is an easy way to fix?

**Comment by martindurant** [comment]
gcsfs could choose to url-encode (quote) the "#", I think s3fs does this. You can work around it by encoding the character ourself, "%23".

"#" is a special character for gcsfs, it is used to select the version of a particular file, if the bucket supports versioning.

**Comment by martindurant** [comment]
Actually is special for all HTTP in general, and in many cases anything after and including the "#" would simply be stripped. Maybe that's what happened and you, effectively, printed the "contents" of the directory (zero bytes).

**Comment by kornosk** [comment]
I see. I was trying `from google cloud import storage` instead and it works so I was very confused. I hope gcsfs would do as s3fs does in the future but for now we may need to work around ourself. Thank you again for your help! @martindurant

**Comment by simonbohnen** [comment]
@martindurant could you point me to the spot in `gcsfs` where the `#` is used for versioning? I would say that even if it is used for versioning, there should be a way to include it in object names. After all, it's only [discouraged](https://cloud.google.com/storage/docs/objects#naming), but not forbidden to use in object names.

**Comment by simonbohnen** [comment]
I would like to do the escaping in gcsfs the same way that it's done in the Google Cloud Storage client library [here](https://github.com/googleapis/python-storage/blob/8a24add52f0bc7dbcb3ec427bd3e4551b3afcbf5/google/cloud/storage/blob.py#L4406), where all characters are escaped. I will submit a PR for this.
