### ISSUE TITLE
gc_fs.open raises FileNotFoundError as difficult to read path

### ISSUE THREAD

**Issue by iuiu34** [fsspec/gcsfs#469]
if you try to open a file that doesn't exist
```py

import gcsfs
import pandas as pd

data_path = 'gs://this/bucket/does/not/exist'
gc_fs = gcsfs.GCSFileSystem(project=self.project, token=self.credentials)

with gc_fs.open(data_path, 'r') as f:
            data = pd.read_csv(f)

```

raises the error

```

FileNotFoundError: b/this/o/bucket%2Ftdoes%2Fnot%2Fexist

```

 

would be easier to read if raised

```

FileNotFoundError: b/this/o/bucket/does/not/exist

```

 

or even better

```

FileNotFoundError: gs://this/bucket/does/not/exist

```

 

changin line 82 in `gcsfs/retry.py` from
```py
path = path.format(*[quote_plus(p) for p in args])
```

to
```py
path = path.format(*args)
```

would solve the problem, there's any reason that i'm unaware, for the `quote_plus` ?

**Comment by martindurant** [comment]
huh, just spotted this message, sorry for not noticing for so long!
The reason for quote_plus, is that the GCS endpoint differentiates the part that's the "command", telling it what you want to do, and the "path", which is just the name of a string. The latter must *not* contain sensitive characters to be unambiguously understood. Sorry, there's nothing we can do about this. It would be possible to recreate the original path from the error returned to us by GCS, with a little work, I suppose.
