### ISSUE TITLE
mv and rename not working as expected

### ISSUE THREAD

**Issue by L1st3r** [fsspec/gcsfs#489]
I create a folder in a bucket  "/my-bucket/folder/" which contains some text files. I then run

`fs.rename("/my-bucket/folder/", "/my-bucket/new_folder", recursive=True)`

Instead of seeing "/my-bucket/new_folder", I see "/my-bucket/new_foldermy-bucket/folder"

That doesn't seem correct. mv does the same thing.

Testing with fsspec and the localfilesystem give the expected result of there being just a "/folder/new_folder" that you would expect

**Comment by ianthomas23** [comment]
This has been fixed by the recent improvements to recursive path expansions in `fsspec`. I have added an explicit test for this in #575.
