### ISSUE TITLE
token="cloud" failing after 2022.7.1

### ISSUE THREAD

**Issue by davideasaf** [fsspec/gcsfs#501]
https://github.com/fsspec/gcsfs/compare/2022.5.0...2022.7.1#diff-ab034e54024ab92b8af1b6538da0baa77f986980ccab9a67a8b3441a1d83cde9R95-R98

The check above does not work with the latest version of `google.auth` according to the docs here: https://google-auth.readthedocs.io/en/stable/reference/google.auth.credentials.html#google.auth.credentials.Credentials

> Most credentials will be invalid until [refresh()](https://google-auth.readthedocs.io/en/stable/reference/google.auth.credentials.html#google.auth.credentials.Credentials.refresh) is called. Credentials can do this automatically before the first HTTP request in [before_request()](https://google-auth.readthedocs.io/en/stable/reference/google.auth.credentials.html#google.auth.credentials.Credentials.before_request).

Checking for validity right after creating the credential object throws False. This was working before because before_request() was being called before a future request to storage.

**Comment by martindurant** [comment]
Does https://github.com/fsspec/gcsfs/pull/487 fix this?

**Comment by davideasaf** [comment]
yes @martindurant . Thank you for pointing me there. Apologies for not seeing that resolution!
