### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by yan-hic** [fsspec/gcsfs#519]
I am using [Quart ](https://quart.palletsprojects.com/en/latest/) in a GCP function and instantiate `gcsfs` like so:
```
@app.before_serving
async def startup():
    app.gs = gcsfs.GCSFileSystem(asynchronous=True)
```
When idle, I have noticed in the logs that `gcsfs` sends a few times the following messages:
```
client_session: <aiohttp.client.ClientSession object at 0x7f1c9d836250>
Unclosed client session
```
Any clue what/why this is sent ? It might be just a warning but I rather close any session properly if possible (in Quart, this would be within a `@app.after_serving` decorated function)

**Comment by martindurant** [comment]
If running aync, you should close the session explicitly when you are done, since del/weakref calls aren't run on the event loop
```python
    await app.gs.session.close()
```

**Comment by yan-hic** [comment]
Thanks Martin but that errors out:
```
Traceback (most recent call last):
  File "C:\Users\ye\AppData\Local\Programs\Python\Python311\Lib\site-packages\quart\app.py", line 1948, in shutdown
    await self.ensure_async(func)()
  File "C:\Users\ye\PycharmProjects\TaxTract\entity-extract\app\main.py", line 54, in stop
    await app.gs.session.close()
          ^^^^^^^^^^^^^^
  File "C:\Users\ye\AppData\Local\Programs\Python\Python311\Lib\site-packages\gcsfs\core.py", line 343, in session
    raise RuntimeError("Please await _connect* before anything else")
RuntimeError: Please await _connect* before anything else
```

**Comment by martindurant** [comment]
Hm, the previous error suggested that this session was being started somewhere... The connect and close calls should be paired.

**Comment by yan-hic** [comment]
Quart's main maintainer just came up with the answer, using a decorator that was new to me:
```
@app.while_serving
async def while_serving():
    app.gs = gcsfs.GCSFileSystem(asynchronous=True)
    yield
    await app.gs.session.close()
```

**Comment by martindurant** [comment]
Glad to know that worked. I don't know `quart` myself, but in general I would love to deprecate extra code for async operation, but it has proven tricky.

**Comment by martindurant** [comment]
https://pypi.org/project/asyncio-atexit/ ?
