### ISSUE TITLE
ResourceWarning: Sending a large body directly with raw bytes might lock the event loop.

### ISSUE THREAD

**Issue by tusharvaswanicoder** [fsspec/gcsfs#524]
Hey Everyone,

Getting this issue from some time. This issue is occuring when we are uploading the data to google cloud bucket using the upload function:

```
ResourceWarning: Sending a large body directly with raw bytes might lock the event loop. You should probably pass an io.BytesIO object instead
  warnings.warn(
```

Please look into this. I think this is coming from the way you are sending the files.
Thanks

**Comment by martindurant** [comment]
Can you please detail what you do to get this warning? It would be good to know where in the gcsfs it originates. Blocking the event loop is not actually a problem in typical gcsfs use, since you are very likely using the sync API anyway, and the loop lives on a thread dedicated to IO (it will be busy sending bytes, could not do other operations anyway).

**Comment by tusharvaswanicoder** [comment]
Yes @martindurant , So we have a fastapi microservice which is using dramatiq as a task queue. Now we call an api and dramatiq start executing a task in that task we download some file from google cloud bucket. Also then finally we upload all the files back to google cloud bucket. So when we upload only then we get this error. And just for the clarity the stack trace shows the error to be originating from aiohttp. This is the only stack trace I get:

```
/usr/local/lib/python3.10/site-packages/aiohttp/payload.py:238: ResourceWarning: Sending a large body directly with raw bytes might lock the event loop. You should probably pass an io.BytesIO object instead
  warnings.warn(
```

Also just for confirmation we commented the lines uploading the things and then the error just went away.

And we were also not worried about this error earlier and we never realised that it was important but then when we sent some good number of requests and then dramatiq just got killed because of that.

Thanks

**Comment by tusharvaswanicoder** [comment]
![image](https://user-images.githubusercontent.com/80880788/216107839-4d76cdaf-98c8-4e7f-b80f-74d9e2efae7f.png)
You said in stackoverflow once that gcsfs does not support async.\

**Comment by martindurant** [comment]
The file-like interface is not, indeed. But methods on the filesystem are. So you are doing some `fs.open(...).write()` kind of operation? This kind of detail will help me.

**Comment by tusharvaswanicoder** [comment]
No I was using fs.upload method

**Comment by martindurant** [comment]
How big is the file in question? Are you passing any kwargs?

**Comment by tusharvaswanicoder** [comment]
No I am not passing any kwargs and the file is sometimes 9mb and sometimes 17mb not more than that yet. Currently we are just testing it and so in production there can be GBs of uploads

**Comment by akshhack** [comment]
@martindurant facing the same exact issue.

**Comment by martindurant** [comment]
Please test with the linked PR

**Comment by tusharvaswanicoder** [comment]
@martindurant Really don't know how to thank you but the things are finally back on track with that PR. Just one more question I have do you think that this issue can be there in other methods also. And also it would be great if you can merge the pull request and maybe issue a new release that would be great.

And also just wanted to ask a question (not relevant to this issue) but is there some function in gcsfs to delete a folder as I cant really find that.

**Comment by martindurant** [comment]
> do you think that this issue can be there in other methods

I patched both places that data is sent. The only outlier is batched file deletion, but those are capped at 100 parts per request, so the payload will always be small.

> maybe issue a new release

We release pretty regularly, it won't be long.

> is there some function in gcsfs to delete a folder as I cant really find that.

`fs.rm(path, recursive=True` is probably what you want. The concept of "folder" is a little unclear for key-value stores like GCS, and sometimes you also need to remove placeholder zero-legth-files. If by "folder" you means bucket, then `rm()` will also work, and you have `rmdir()` to delete a empty bucket.

**Comment by tusharvaswanicoder** [comment]
Thanks @martindurant again for helping us.
