### ISSUE TITLE
Modified gives incorrect results

### ISSUE THREAD

**Issue by Koncopd** [fsspec/gcsfs#526]
Probably an issue with timezones.

![image](https://user-images.githubusercontent.com/3065736/216830746-66089a74-7cbe-48ea-b6c5-f0be57f24156.png)
Modifed time in the local timezone (CET or UTC+1)

![image](https://user-images.githubusercontent.com/3065736/216830595-64adbab9-5ad8-45d9-b4f4-6c783d585a50.png)
And `"updated"` from `stat` gives different (and correct) result from `modified` in utc.

**Comment by martindurant** [comment]
I believe the linked PR does this right now. This should have been simpler to acomplish!
