### ISSUE TITLE
Random `ValueError: I/O operation on closed file` from `aiohttp`.

### ISSUE THREAD

**Issue by tasansal** [fsspec/gcsfs#539]
Hello,

We have a workflow that writes to chunks of a Zarr file using multiprocessing.

1. We create a Zarr array on GCS.
2. We generate chunk boundary slices to pass into the multiprocessing pool.
3. We write to axis 0 and 1 chunks from multiple processes. We always write axis 2 in full.

The minimal workflow is below. This doesn't cause the issue because of the small scale. However, some of our arrays are much larger than this, like shape `(4000, 10000, 5000)`, and we use more cores to do the work. This again works ok most of the time, but occasionally (about 20-30% of the time) we get a `ValueError: I/O operation on closed file` from `aiohttp`.

We tried to trace the error and this is how it goes:
1. The array[slice_] = data gets called
2. This in the end calls GCSFileSystem code [here](https://github.com/fsspec/gcsfs/blob/main/gcsfs/core.py#L396)
3. The client here is an `fsspec` client from [here](https://github.com/fsspec/filesystem_spec/blob/834115f2b91f61d09004beb1bfd46d705a201c2b/fsspec/implementations/http.py#L29)
4. Which is an `aiohttp`'s `ClientSession` [here](https://github.com/aio-libs/aiohttp/blob/ae7703cefd1f8c8ad02bfc21cdc92c367f2666b9/aiohttp/client.py#L164)
5. It tries to get the size of the request [here](https://github.com/aio-libs/aiohttp/blob/6da04694fd87a39af9c3856048c9ff23ca815f88/aiohttp/client_reqrep.py#L474)
6. Then in the size function, the cursor position `tell` function raises the error [here](https://github.com/aio-libs/aiohttp/blob/6da04694fd87a39af9c3856048c9ff23ca815f88/aiohttp/payload.py#L364)

The error is thrown while retrieving the first position of the payload, saying the file is already closed for the I/o operation. 

We are lost here and can't figure out where the issue occurs. Could the HTTP request be deleted/closed prematurely somewhere in the pipeline? 

This doesn't happen persistently and is a random occurrence from different workers.

```python
import multiprocessing as mp
from itertools import repeat

import numpy as np
import zarr


mp.set_start_method("spawn")


def write_chunk(array, slice_):
    """Generate mock data and write."""
    data = np.random.uniform(size=(64, 64, 1024)).astype("float32")
    array[slice_] = data


if __name__ == "__main__":
    path = "gs://bucket/prefix/array.zarr"

    array = zarr.open_array(
        store=path,
        mode="w",
        shape=(512, 512, 1024),
        chunks=(64, 64, 128),
        dtype="float32",
    )

    # Generate chunk slice iterator
    slices = []
    for i in range(8):  # n_chunks axis=0
        for j in range(8):  # n_chunks axis=1
            i_slice = slice(i * 64, (i + 1) * 64)
            j_slice = slice(j * 64, (j + 1) * 64)
            k_slice = slice(None)  # we write full slices on axis=2

            slices.append((i_slice, j_slice, k_slice))

    # Send work to mp pool.
    with mp.Pool(10) as p:
        p.starmap(write_chunk, zip(repeat(array), slices))
```

# Environment
We tried with latest versions of `fsspec` and `gcsfs`.

**Comment by martindurant** [comment]
Hm, it feels like a network problem - which means that this should be a retry situation.
Is the exception a base ValueError or some aiohttp-wrapped variant? 

To be sure: this is writing whole chunks in each task, there should be no concurrent writes to the same key, right?

**Comment by tasansal** [comment]
> Hm, it feels like a network problem - which means that this should be a retry situation.
> 
> Is the exception a base ValueError or some aiohttp-wrapped variant? 
> 
> 
> 
> To be sure: this is writing whole chunks in each task, there should be no concurrent writes to the same key, right?

Thanks for the quick reply @martindurant 

Yes it seems like it's a base ValueError. Here: 

Only writing whole chunks, yes. 

It happens quite often. We ingest tens if not hundreds of terabytes into zarr, and happens about 10% of the time.

**Comment by tasansal** [comment]
Whoops sorry. I did some more digging; here is a more accurate tracing.

The last call in `aiohttp` is [here](https://github.com/aio-libs/aiohttp/blob/6da04694fd87a39af9c3856048c9ff23ca815f88/aiohttp/payload.py#L364)

Which runs a `.tell()` on a `BytesIO` object. Then [this](https://github.com/python/cpython/blob/95ee7c47ab53eb0e26f2b2b4f681015f49c0bff7/Modules/_io/bytesio.c#L38) is raised from `cpython`.

Somehow the BytesIO context is closed at some point. 

I wonder if https://github.com/aio-libs/aiohttp/issues/3654 is related?

I don't yet understand how `fsspec`, by extension, `gcsfs` interacts with `aiohttp`.

Some questions:
1. Who is in charge of opening / closing the connection?
2. If `fsspec` is in charge, how can we alleviate this?
3. Is this a bug in `aiohttp`? The issue I linked above sounds like this is expected behavior. Unfortunately, the issue got stale.

**Comment by tasansal** [comment]
> > > Here:
> 
> ^ the trace wasn't included, or didn't render

Whoops sorry. I did some more digging; here is a more accurate tracing.

The last call in `aiohttp` is [here](https://github.com/aio-libs/aiohttp/blob/6da04694fd87a39af9c3856048c9ff23ca815f88/aiohttp/payload.py#L364)

Which runs a `.tell()` on a `BytesIO` object. Then [this](https://github.com/python/cpython/blob/95ee7c47ab53eb0e26f2b2b4f681015f49c0bff7/Modules/_io/bytesio.c#L38) is raised from `cpython`.

Somehow the BytesIO context is closed at some point. 

I wonder if https://github.com/aio-libs/aiohttp/issues/3654 is related?

I don't yet understand how `fsspec`, by extension, `gcsfs` interacts with `aiohttp`.

Some questions:
1. Who is in charge of opening / closing the connection?
2. If `fsspec` is in charge, how can we alleviate this?
3. Is this a bug in `aiohttp`? The issue I linked above sounds like this is expected behavior. Unfortunately, the issue got stale.

**Comment by martindurant** [comment]
All gcsfs calls go through the client .request() method. This is a coroutine, and gcsfs's blocking API waits for it to finish. Since https://github.com/fsspec/gcsfs/pull/525 , the payload can be wrapped in a BytesIO, following an aiohttp warning saying that you should, but this is live throughout waiting for aiohttp to work. The BytesIO's initial position is always 0.

At a hunch, your situation might be triggered by a retry, as in the linked issue: aiohttp gets to the end of the BytesIO "file", closes it, but the call fails in a retriable way. I'll make you a plausible diff to try, one minute.

**Comment by martindurant** [comment]
https://github.com/fsspec/gcsfs/pull/540

**Comment by tasansal** [comment]
@martindurant, thanks for the great explanation. We will give it a try.

Would not closing the BytesIO cause a problem?

P.S.
It may take a week or two to get it in and test it in our dev env. Will keep you posted.

**Comment by martindurant** [comment]
> Would not closing the BytesIO cause a problem?

Not at all, the memory is freed when the object goes out of scope or gets garbage collected - maybe a few python statements later, but there will be no ill consequences.

**Comment by tasansal** [comment]
@martindurant we were able to test this. Now we are getting this error:

```python
INFO - gcsfs.retry.HttpError: Invalid multipart request with 0 mime parts., 400
```

Looks like it is retrying now and hitting another error. Again, happens occasionally, can't deterministically replicate it.

The exception raised is [here](https://github.com/fsspec/gcsfs/blob/b968445be614464dc14160fc6a85965947448d15/gcsfs/retry.py#L103)

Anything else we can get you to help debug?
