### ISSUE TITLE
Not working async, typo in docs

### ISSUE THREAD

**Issue by racinmat** [fsspec/gcsfs#542]
Docs in https://gcsfs.readthedocs.io/en/latest/#async mention `gcs.set_session()`, but there us only `gcs._set_session()`.
The demo itself is not working, I am running this code
```python
    import asyncio
    from gcsfs import GCSFileSystem
    loop = asyncio.get_event_loop()

    async def run_program(loop):
        gcs = GCSFileSystem(project='ppt-ctodl-cto-data-40', asynchronous=True, loop=loop)
        await gcs._set_session()
        csv_files = gcs.glob('ds_hcs-nlp_test_by-date_csv/**/*.csv.gz')
        print('done')

    asyncio.run(run_program(loop))  # or call from your async code
```
and it crashes with
```
RuntimeError: Loop is not running
2023-04-25 15:47:11,021 [MainThread] - ERROR    asyncio: Unclosed client session
```

**Comment by racinmat** [comment]
Thanks! So I don't need to supply the loop? I see.
I don't have time right now, but I'll send PR if I'll have time to fix it sometimes this week.

**Comment by martindurant** [comment]
No, _open is not an async function, certainly not an async context. Since files have internal state (location, buffers), they are not appropriate for concurrent use. Newly, there is an async streaming class (for reading beginning to end only) via open_async(). The naming convention is a little weird here, due to history.

**Comment by racinmat** [comment]
And wheere can I find that streaming class `open_async()`? I don't see it in the repo, the github search is not showing it, and neither do docs.

**Comment by martindurant** [comment]
Oh, sorry - that was done for s3fs but not gcsfs. Another thing on my list.

**Comment by racinmat** [comment]
@martindurant  I found some time and made a PR
