### ISSUE TITLE
Errors when deleting a directory with huge number of files

### ISSUE THREAD

**Issue by mil-ad** [fsspec/gcsfs#558]
I'm trying to delete a path witth `fs.rm(some_path, recursive=True)` that has a huge number of files. gcsfs in general can deal with this well and finishes the delete in like 30 secs while `gsutil -m rm -r` takes almost an hour! However, I do this delete ocassionally in a long loop and eventually I see error below:

```
  File "/home/milad/micromamba/envs/foo/lib/python3.8/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/milad/micromamba/envs/foo/lib/python3.8/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/home/milad/micromamba/envs/foo/lib/python3.8/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/home/milad/micromamba/envs/foo/lib/python3.8/site-packages/gcsfs/core.py", line 987, in _rm
    raise exs[0]
  File "/home/milad/micromamba/envs/foo/lib/python3.8/site-packages/gcsfs/core.py", line 952, in _rm_files
    raise OSError(out)
OSError: {'We encountered an internal error. Please try again.'}
```

I also got this error once:

```
OSError: {"You have exceeded your bucket's IO capacity. Please follow the request rate and access distribution guidelines at https://cloud.google.com/storage/docs/hotspotting to scale your workload."}
```

Probably related to the exponential backoff that Google recommends? Is that implemented in gcsfs? I also tried changing the `batchsize` argument of `rm` but it didn't make a difference.

---
I'm using version `2022.7.1` if that's relevant

**Comment by martindurant** [comment]
Such a call should automatically be retriable, assuming the server is returning 408/427.
Can you please turn on logging, to see if retries are happening, to what errors are coming back? The following code can do it:
```
import fsspec
fsspec.utils.setup_logging(logger_name="gcsfs")
```

**Comment by mil-ad** [comment]
I'll do that and get back to you. 🫡

Google really doesn't want you to hit this rate limit and in the past I have seen them reducing the limit when you hit it a bunch of times. So even if it is retriable I think it makes sense to implement their endorsed exponential back off.

**Comment by martindurant** [comment]
Yes, our retry code does exponential backoff 
```
await asyncio.sleep(min(random.random() + 2 ** (retry - 1), 32))
```
(retry is 0->6 by default)

**Comment by martindurant** [comment]
Hm, OK - this is a special case I had not considered. There are errors associated with the individual delete operations within each request, but the overall request apparently succeeds.

Do some of the files get removed each time?

**Comment by mil-ad** [comment]
yeah I think so but it fails at some random point

**Comment by martindurant** [comment]
It would come down, I think, to wrapping the `for chunk` loop within `_rm_files` in an outer loop and filtering out the paths that need to be resubmitted. The exponential fallback policy would be the same as currently. The only tricky [art would be distinguishing errors that should be retried (presumably only code 427 in this context?) from other errors that should be raised.

**Comment by mil-ad** [comment]
> The exponential fallback policy would be the same as currently.

I haven't looked at the code carefulluy but shoulddn't backoff happen with a normal sync sleep instead of "async sleep"?

**Comment by martindurant** [comment]
> shouldn't backoff happen with a normal sync sleep instead of "async sleep"

Absolutely not - we are waiting for responses to other requests, which may well succeed (or potentially not even be to the same service). We do not want to block the thread for that.

**Comment by mil-ad** [comment]
Makes sense. Please do ping me if you have a branch that fixes this. We're keen to use this and help with the debugging. Unfortunately I'm not familiar with the codebase to have a go at fixing it myself.

**Comment by slevang** [comment]
> It would come down, I think, to wrapping the `for chunk` loop within `_rm_files` in an outer loop and filtering out the paths that need to be resubmitted. The exponential fallback policy would be the same as currently. The only tricky part would be distinguishing errors that should be retried (presumably only code 427 in this context?) from other errors that should be raised.

@martindurant could you provide just a little more guidance on the architecture you're envisioning here?

I would love to get this fixed and would be happy to attempt a PR. It's the one remaining weird flaky issue I keep running into with this otherwise amazing library. It happened the other day trying to overwrite a not very large zarr with `mode="w"`. This should absolutely be retriable.

**Comment by slevang** [comment]
Following up with a trivial MCVE of where I keep running into this error:
```python
import dask.array

gcs_path = "gs://your-bucket/test.zarr"

x = dask.array.ones((5000, 100), chunks=(1, -1))
x.to_zarr(gcs_path, overwrite=True)
# Second attempt to batch remove 5000 files will always fail on cold bucket
x.to_zarr(gcs_path, overwrite=True)

OSError: ['We encountered an internal error. Please try again.']
```

In this particular example it is about 15 files +- that are left over from the failed deletion. As you said @martindurant the solution seems to be to catch and filter out these errors then retry. I poked around the `_rm_files` code a little but couldn't figure it out in the time I had.
