### ISSUE TITLE
The info object in GCSFS does not have mtime/ctime

### ISSUE THREAD

**Issue by cvm-a** [fsspec/gcsfs#559]
This is expected by the PyArrow FSSpecHandler _create_file_info method.

This is the GCSFS version of https://github.com/fsspec/filesystem_spec/issues/526

**Comment by martindurant** [comment]
It appears that GCS provides fields 'timeCreated' and 'updated'. Would you like to make PR aliasing these to the format/names expected by pyarrow?

**Comment by cvm-a** [comment]
Sure, I can give that a shot
