### ISSUE TITLE
`find` performance regression

### ISSUE THREAD

**Issue by slevang** [fsspec/gcsfs#560]
Performing `fs.find()` on a root containing many objects got **way** slower after #531. For a path with ~200k objects, I timed this at 24s on `2023.1.0` and 10m on `2023.3.0`. Once the [object listing](https://github.com/fsspec/gcsfs/blob/main/gcsfs/core.py#L1232) is complete, we end up stuck in this [while loop](https://github.com/fsspec/gcsfs/blob/main/gcsfs/core.py#L1243) for ages. I don't understand the cache modifications here well enough to know the fix but I hope it will be simple since this was only a few lines of code added.

I found this after much debugging when my `to_zarr(..., mode="a")` calls suddenly hung, where the zarr metadata consolidation step is eventually iterating through every key in the store via an `fs.find` op.

**Comment by slevang** [comment]
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
  1190                                               @profile
  1191                                               async def _find(
  1192                                                   self, path, withdirs=False, detail=False, prefix="", versions=False, **kwargs
  1193                                               ):
...
  1230    376067     234576.5      0.6      0.0                  listing = cache_entries.setdefault(parent, [])
  1231    188045  545750484.0   2902.2     98.2                  if previous not in listing:
  1232    188045     489787.0      2.6      0.1                      listing.append(previous)

```
This is from directly running `fs.find` on the root of the zarr directory, which has one variable with 200k chunks.

**Comment by martindurant** [comment]
OK, this is *good news*, we should be able to replace `in` with the list with a set to make it much much faster.

**Comment by slevang** [comment]
Good point, I'll give it a try. Thanks
