### ISSUE TITLE
Stale cache info leading to failing isfile check

### ISSUE THREAD

**Issue by ianthomas23** [fsspec/gcsfs#562]
Whilst trying to get the new abstract test harness working on gcsfs, I have come across an issue of a `gcs.isfile()` test erroneously failing.

If you add the following code to `gcsfs/tests/test_core.py`:
```python
def test_stale_isfile(gcs):
    source = TEST_BUCKET + "/source"
    gcs.mkdir(source)
    gcs.touch(source + "/file2")

    target = TEST_BUCKET + "/target"
    assert not gcs.exists(target)
    gcs.touch(target + "/dummy")
    assert gcs.isdir(target)

    target_file2 = target + "/file2"
    gcs.cp(source + "/file2", target)

    #gcs.find(target, withdirs=True)

    assert gcs.isfile(target_file2)
```
and run it using `pytest -v gcsfs/tests/test_core.py::test_stale_isfile` then the `isfile` assert fails. If you then remove the commented-out line to force a `gcs.find` then the test passes.

**Comment by martindurant** [comment]
find() does possibly do some rewriting of dircache (as in #561 ), so that's what I would look at first. `cp()` is supposed to reset the dircache for the target, so the other thing to check is whether `gcs.invalidate_cache()` before `isfile` gives the correct result.

**Comment by ianthomas23** [comment]
Thanks for the pointers, it turns out that the `cp()` wasn't invalidating the dircache for the target. Solution is in PR #564.
