### ISSUE TITLE
Is it needed to be so strict about dependency on fsspec

### ISSUE THREAD

**Issue by honnix** [fsspec/gcsfs#584]
Currently, both gcsfs and s3fs pin to specific version of fsspec. This is troublesome when both of them need to be installed in the same environment because they may require different fsspec versions. At the time of writing, s3fs has `2023.9.2` but gcsfs has `2023.9.1`, so as a user of both packages, it is required to pin both s3fs and gcsfs, in order to get a compatible fsspec version. While pinning is usually not a problem for an application, it may create trouble for a library because user of that particular library will likely have conflict when installing it together with other libraries, and so on so forth the issue gets propagated.

So the question is, is it strictly needed to pin to a specific version of fsspec? Maybe it is, due to compatibility requirement?

 Thank you.

**Comment by martindurant** [comment]
I'm afraid it is generally desirable to keep the version numbers together. I am slightly late releasing gcsfs this round, but the three packages normally go out within a day of each other. I'll have a release by the end of today.

Note that if you use conda/mamba to make environments rater than pip, you should expect not to have to worry too much about pinning versions as the solver will always find something consistent.
