### ISSUE TITLE
Release 2023.10.0 and consider relaxing fsspec dependency

### ISSUE THREAD

**Issue by bolkedebruin** [fsspec/gcsfs#587]
The parent `fsspec` 2023.10.0 version has been released. It would be nice to have a release of `gcsfs` as well. At the same time it might be worth considering relaxing the requirements on the parent project.

The challenge is that if a fix is released in one the sibling projects (like s3fs in this case) which bumps the requirement of `fsspec`  it cannot be upgraded if you are using one of the other siblings (e.g. gcsfs) as well. This is happening now. `s3fs` updatef its dependency to aiobotocore 2.7.0 which in turn allowed a more generous spread of botocore versions. This prompted a release of both `fsspec` and `s3fs` to 2023.10.0, but now if you are also dependent on `gcsfs` you are being held back.

Alternatively, a synchronized release is an option. But this might be significant more work.

**Comment by bolkedebruin** [comment]
Gotcha, I know the burden of doing releases. So thank you.

**Comment by martindurant** [comment]
gcsfs is out on pypi
