### ISSUE TITLE
Filename with slashes in the path are getting URL encoded, causing them to fail

### ISSUE THREAD

**Issue by finbarrtimbers** [fsspec/gcsfs#600]
Hey folks, 

I'm running into an issue where I can't open a file on GCS because the filename is being modified. The following fails:

```
gcsfs.GCSFileSystem().info('gs://my_bucket/v6/comparisons_diff_prompt.csv')
```

It gives the error `FileNotFoundError: b/active-learning-comparisons/o/v6%2Fcomparisons_diff_prompt.csv`. However, the file does exist, and can be read via Pandas (`pd.read_csv('gs://my_bucket/v6/comparisons_diff_prompt.csv'`).

Am I doing something wrong with the path being provided to `gcsfs`?

**Comment by finbarrtimbers** [comment]
Sorry, I'm wrong. This is my mistake. URL does not, actually, exist.

**Comment by martindurant** [comment]
Thanks for updating :)
