### ISSUE TITLE
Error introduced in 2024.3.0

### ISSUE THREAD

**Issue by classner** [fsspec/gcsfs#615]
Hi!

We just started noticing tests failing over the weekend after upgrading to fsspec and gcsfs 2024.3.0. The errors look as follows:

```
File "gcsfs/core.py", line 1509, in _initiate_upload
    self.content_type,
AttributeError: 'GCSFile' object has no attribute 'content_type'
Exception ignored in: <function AbstractBufferedFile.__del__ at 0x7fd26dbdf400>
```

Not sure whether to report this here or for gcsfs - I assume the structure of `gcsfs.core` has changed the `_initiate_upload` function?

**Comment by martindurant** [comment]
This is happening during `__del__`, so likely during interpreter shutdown. Do you have the code? Likely it isn't affecting anything? I can certainly look into it.

cc https://github.com/fsspec/gcsfs/pull/606 @pgcamus possibly related

**Comment by classner** [comment]
Interesting! Updating to 2024.3.1 fixes this issue. There was definitely an issue triggered by 2024.3.0 affecting us and 2024.3.1 is fine - according to logs this was the likely culprit.
